<a href="https://colab.research.google.com/github/PabloDiosquez/Intermediate_Python_Course/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

The Basics

In [23]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [14]:
# Get Size
b.itemsize

8

In [15]:
# Get total size
b.nbytes

48

In [18]:
# Get number of elements
print(a.size)
print(b.size)

3
6


Accessing/Changing specific elements, rows, columns, etc

In [46]:
a = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
# Get specific element [r,c]
print(a[1,4])
print(a[1,-3])

12
12


In [26]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column
a[: ,2]

array([ 3, 10])

In [33]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1: 6 : 2]

array([2, 4, 6])

In [51]:
a[1,4] = 20

a[:,2] = [1,2]
# print(a)

a[0,:] = [0]*7
print(a)

[[ 0  0  0  0  0  0  0]
 [ 8  9  2 11 20 13 14]]


3D example


In [39]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# Get a specific element (work outside in)
b[1,0,1]

6

In [44]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Initializing Different Types of Arrays

In [53]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# All 1s matrix
np.ones((4,2,2), dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [56]:
# Any other number 
np.full((3,3),-1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [57]:
# Any other number (full_like)
np.full_like(a,-7)

array([[-7, -7, -7, -7, -7, -7, -7],
       [-7, -7, -7, -7, -7, -7, -7]])

In [58]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.11288097, 0.36972366],
       [0.12250015, 0.73570631],
       [0.28098707, 0.69900864],
       [0.57133245, 0.36469858]])

In [59]:
# Random integer values
np.random.randint(low=-12,high=10,size=(4,4))

array([[ -5,  -3,   0, -10],
       [ -5,   0,   7,   2],
       [ -1,  -4,  -2,  -8],
       [  3, -11,   6,   3]])

In [60]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [70]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = -1
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 0.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0. -1.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


Be careful when copiyng arrays! ⚠

In [73]:
a = np.array([1,2,3])
b = a.copy()
a[0] = 101
print(a)
print(b)

[101   2   3]
[1 2 3]
