<a href="https://colab.research.google.com/github/PabloDiosquez/Intermediate_Python_Course/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

The Basics

In [3]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [14]:
# Get Size
b.itemsize

8

In [15]:
# Get total size
b.nbytes

48

In [18]:
# Get number of elements
print(a.size)
print(b.size)

3
6
