<a href="https://colab.research.google.com/github/PabloDiosquez/Intermediate_Python_Course/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

The Basics

In [ ]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [ ]:
# Get Size
b.itemsize

8

In [ ]:
# Get total size
b.nbytes

48

In [ ]:
# Get number of elements
print(a.size)
print(b.size)

3
6


Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get specific element [r,c]
print(a[1,4])
print(a[1,-3])

12
12


In [ ]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[: ,2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1: 6 : 2]

array([2, 4, 6])

In [ ]:
a[1,4] = 20

a[:,2] = [1,2]
# print(a)

a[0,:] = [0]*7
print(a)

[[ 0  0  0  0  0  0  0]
 [ 8  9  2 11 20 13 14]]


3D example


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get a specific element (work outside in)
b[1,0,1]

6

In [ ]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [ ]:
# Any other number 
np.full((3,3),-1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
# Any other number (full_like)
np.full_like(a,-7)

array([[-7, -7, -7, -7, -7, -7, -7],
       [-7, -7, -7, -7, -7, -7, -7]])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.11288097, 0.36972366],
       [0.12250015, 0.73570631],
       [0.28098707, 0.69900864],
       [0.57133245, 0.36469858]])

In [ ]:
# Random integer values
np.random.randint(low=-12,high=10,size=(4,4))

array([[ -5,  -3,   0, -10],
       [ -5,   0,   7,   2],
       [ -1,  -4,  -2,  -8],
       [  3, -11,   6,   3]])

In [ ]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = -1
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 0.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0. -1.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


Be careful when copiyng arrays! ⚠

In [ ]:
a = np.array([1,2,3])
b = a.copy()
a[0] = 101
print(a)
print(b)

[101   2   3]
[1 2 3]


**Mathematics**

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
a + 2

array([3, 4, 5, 6])

In [6]:
a - 2

array([-1,  0,  1,  2])

In [7]:
a * 2

array([2, 4, 6, 8])

In [8]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [9]:
b = np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [10]:
a + b

array([2, 2, 4, 4])

In [11]:
a ** 2

array([ 1,  4,  9, 16])

In [12]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.m

**Linear Algebra**

In [15]:
a = np.ones((2,3))
print(f'a: {a}')

b = np.full((3,2),2)
print(f'b: {b}')

ab = np.matmul(a,b)
print(f'a*b: {ab}')

a: [[1. 1. 1.]
 [1. 1. 1.]]
b: [[2 2]
 [2 2]
 [2 2]]
a*b: [[6. 6.]
 [6. 6.]]


In [17]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

**Statistics**

In [18]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [19]:
np.min(stats)

1

In [20]:
np.max(stats)

6

In [22]:
np.max(stats,axis=1)

array([3, 6])

In [24]:
np.sum(stats,axis=0)

array([5, 7, 9])

**Reorganizing Arrays**

In [31]:
before = np.array([[1,2,3],[4,5,6]])
print(f'before: {before}\n')

after = before.reshape((3,2))
print(f'after: {after}')

before: [[1 2 3]
 [4 5 6]]

after: [[1 2]
 [3 4]
 [5 6]]
