<a href="https://colab.research.google.com/github/PabloDiosquez/Intermediate_Python_Course/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

The Basics

In [23]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [14]:
# Get Size
b.itemsize

8

In [15]:
# Get total size
b.nbytes

48

In [18]:
# Get number of elements
print(a.size)
print(b.size)

3
6


Accessing/Changing specific elements, rows, columns, etc

In [24]:
a = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
# Get specific element [r,c]
a[1,2]

10

In [26]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column
a[: ,2]

array([ 3, 10])

In [33]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1: 6 : 2]

array([2, 4, 6])

In [38]:
a[1,4] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 20 13 14]]


In [39]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# Get a specific element (work outside in)
b[1,0,1]

6

In [44]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
